CREATE TABLE users (
    id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    full_name NVARCHAR(255) NOT NULL,
    email NVARCHAR(255) NOT NULL UNIQUE,
    phone NVARCHAR(50) NULL,
    password_hash NVARCHAR(255) NOT NULL,
    role NVARCHAR(30) NOT NULL,
    assigned_facility_id UNIQUEIDENTIFIER NULL,
    status NVARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    created_by NVARCHAR(100) NULL, updated_by NVARCHAR(100) NULL, version BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE activity_logs (
    id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), user_id UNIQUEIDENTIFIER NULL, action NVARCHAR(80) NOT NULL,
    entity_type NVARCHAR(80) NULL, entity_id UNIQUEIDENTIFIER NULL, description NVARCHAR(1000) NULL, ip_address NVARCHAR(64) NULL,
    created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    created_by NVARCHAR(100) NULL, updated_by NVARCHAR(100) NULL, version BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX ix_activity_logs_user_created_at ON activity_logs(user_id, created_at);
