CREATE TABLE facilities (
    id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), name NVARCHAR(255) NOT NULL, address NVARCHAR(500) NULL,
    phone NVARCHAR(50) NULL, description NVARCHAR(1000) NULL, status NVARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    created_by NVARCHAR(100) NULL, updated_by NVARCHAR(100) NULL, version BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE unit_types (
    id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), name NVARCHAR(150) NOT NULL, width DECIMAL(10,2) NULL,
    length DECIMAL(10,2) NULL, height DECIMAL(10,2) NULL, description NVARCHAR(1000) NULL,
    min_monthly_price DECIMAL(19,2) NOT NULL, max_monthly_price DECIMAL(19,2) NOT NULL,
    created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    created_by NVARCHAR(100) NULL, updated_by NVARCHAR(100) NULL, version BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE storage_units (
    id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), facility_id UNIQUEIDENTIFIER NOT NULL, unit_type_id UNIQUEIDENTIFIER NOT NULL,
    code NVARCHAR(80) NOT NULL, floor NVARCHAR(50) NULL, location NVARCHAR(255) NULL, monthly_price DECIMAL(19,2) NOT NULL,
    status NVARCHAR(30) NOT NULL DEFAULT 'AVAILABLE', created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), created_by NVARCHAR(100) NULL, updated_by NVARCHAR(100) NULL, version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_storage_units_facility FOREIGN KEY (facility_id) REFERENCES facilities(id),
    CONSTRAINT fk_storage_units_type FOREIGN KEY (unit_type_id) REFERENCES unit_types(id),
    CONSTRAINT uq_storage_unit_code UNIQUE (facility_id, code)
);
CREATE INDEX ix_storage_units_scope ON storage_units(facility_id, unit_type_id, status);
